global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node-explorer"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "app"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:5000"]
